path:
    "/path/to/reads/"

TE:
    RTE_name: "/path/to/RTE_name.fasta"

TEdb:
    "/path/to/TE_database/transposondb.fasta"

# must include "genomic"
test_genome:
    "test_genome_genomic.fna"

# subfolders with taxon names as below (self and nonself)
taxdb_path:
    "/path/to/genomes/"

# size of largest genome included
db_size:
    "3000000000"

# taxon of test genome, e.g. 'mammal'
self:
    "selftaxon"

# taxon of potential contamination, e.g. 'nematode'
nonself:
    "nonselftaxon"
