# dir must contain fastq files
path:
    "/path/to/fastq_files/"

# RTE name and path to fasta file; modify "RTE_name" on both sides; name of RTE and of fasta file the same + ".fasta"
TE:
    RTE_name: "/path/to/RTE_name.fasta"

# path to transposon database; must include your RTE ("RTE_name")
TEdb:
    "/path/to/repeat_database.fasta"

# name of genome to be tested; must include "genomic"; although genome should be gzipped don't append ".gz" here
test_genome:
    "nameofgenome_genomic.fna"

# path to folder with genome assemblies; subfolders must be named after taxa below (self and nonself) and contain gzipped asseblies
taxdb_path:
    "/path/to/genomes/"

# Size of largest genome in two databases to compare in bp
db_size:
    "3000000000"

# Taxon of genome to be tested
self:
    "mammal"

# Suspected taxon of contamiation 
nonself:
    "nematode"

# Accessions and fragment length (read lengths + insert size)
acc:
    SRRXXXXXX: "XXX"  
    SRRXXXXXX: "XXX"
