path:
    "/PATH/TO/RAW/READS/"

TE:
    RTE:
        "/PATH/TO/RTE.fasta"

TEdb:
    "/PATH/TO/Repbase.fasta"

test_genome:
    "species.genomic.fna"

taxdb_path:
    "/PATH/TO/GENOMES"

db_size:
    "dbsize_in_bp"

non-self:
    "non-self_taxon"
self:
    "self_taxon"

#only HiSeq 2000
acc:
    SRR######: "InsertSize+AvgSpotLen"
    SRR######: "InsertSize+AvgSpotLen"
    SRR######: "InsertSize+AvgSpotLen"

