read_path:
    "/path/to/fastq-files/"

TE:
    RTE_name: "RTE_name.fasta"

# include same RTE from other species for less restrained reciprocal search
recip_TEs: 
    "all_RTE_names_from_other_species.fasta"

TEdb:
    "/path/to/transposondb.fasta"

# must include "genomic"
test_genome:
    "test_genome.genomic.fa"

# path to assemblies; dir must contain subfolders named after taxa below (self and nonself)    
taxdb_path:
    "/path/to/genomes/"

db_size:
    "3000000000"

#taxon of test genome, e.g. 'mammal'
self:
    "taxon"

# taxon of potential contaminants, e.g. 'nematode'
nonself:
    "taxon"
