read_path:
    #"fastq/"
    "/home/sdunemann/projects/RTE1/reciprocal_blastn/19_LoaLongReads/AviRTE/00_fastq/"

TE:
    BovB: "BovB.fasta"

recip_TEs: 
    "all_BovBs.fasta"

TEdb:
    "~/db/TE_databases/repbase230918.fasta"

test_genome:
    "loa_loa.PRJNA60051.WBPS6.genomic.fa"

taxdb_path:
    "/home/sdunemann/db/genomes/"

db_size:
    "1595295449"

self:
    "nematode"

nonself:
    "bird"
